### ISSUE TITLE
[Bug]: Server crash after teleport

### ISSUE THREAD

**Issue by Zach67** [TheIllusiveC4/CurioOfUndying#7]
### Minecraft Version

1.17.1

### What happened?

I teleport to a waystone I have in the nether named "Nether1" and it crashes the server and throws this error:

"java.lang.IllegalStateException: Duplicate Capability Key: curios:item top.theillusivec4.curioofundying.CurioOfUndyingMod$2@d539316
	at net.minecraftforge.event.AttachCapabilitiesEvent.addCapability(AttachCapabilitiesEvent.java:71) ~[forge-1.17.1-37.0.126-universal.jar%23147!:?] {re:classloading,pl:eventbus:A}
	at top.theillusivec4.curioofundying.CurioOfUndyingMod.attachCapabilities(CurioOfUndyingMod.java:111) ~[curioofundying-forge-1.17.1-5.3.0.0.jar%2360!:task ':jar' property 'archiveVersion'] {re:mixin,re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_726_CurioOfUndyingMod_attachCapabilities_AttachCapabilitiesEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:581) ~[forge-1.17.1-37.0.126-universal.jar%23147!:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:575) ~[forge-1.17.1-37.0.126-universal.jar%23147!:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.common.capabilities.CapabilityProvider.doGatherCapabilities(CapabilityProvider.java:85) ~[forge-1.17.1-37.0.126-universal.jar%23147!:?] {re:computing_frames,re:mixin,re:classloading}
	at net.minecraftforge.common.capabilities.CapabilityProvider.getCapabilities(CapabilityProvider.java:93) ~[forge-1.17.1-37.0.126-universal.jar%23147!:?] {re:computing_frames,re:mixin,re:classloading}
	at net.minecraftforge.common.capabilities.CapabilityProvider.areCapsCompatible(CapabilityProvider.java:105) ~[forge-1.17.1-37.0.126-universal.jar%23147!:?] {re:computing_frames,re:mixin,re:classloading}
	at net.minecraft.world.item.ItemStack.m_41744_(ItemStack.java:435) ~[server-1.17.1-20210706.113038-srg.jar%23143!:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack}
	at net.minecraft.world.item.ItemStack.m_41728_(ItemStack.java:423) ~[server-1.17.1-20210706.113038-srg.jar%23143!:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack}
	at net.minecraft.world.entity.LivingEntity.m_21319_(LivingEntity.java:2350) ~[server-1.17.1-20210706.113038-srg.jar%23143!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:blue_skies.mixins.json:LivingEntityMixin,pl:mixin:APP:caelus.mixins.json:MixinLivingEntity,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:curioofundying.mixins.json:LivingEntityMixin,pl:mixin:APP:enhancedcelestials.mixins.json:MixinLivingEntity,pl:mixin:APP:supplementaries.mixins.json:LivingEntityLadderMixin,pl:mixin:A}
	at net.minecraft.world.entity.LivingEntity.m_21315_(LivingEntity.java:2322) ~[server-1.17.1-20210706.113038-srg.jar%23143!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:blue_skies.mixins.json:LivingEntityMixin,pl:mixin:APP:caelus.mixins.json:MixinLivingEntity,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:curioofundying.mixins.json:LivingEntityMixin,pl:mixin:APP:enhancedcelestials.mixins.json:MixinLivingEntity,pl:mixin:APP:supplementaries.mixins.json:LivingEntityLadderMixin,pl:mixin:A}
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2231) ~[server-1.17.1-20210706.113038-srg.jar%23143!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:blue_skies.mixins.json:LivingEntityMixin,pl:mixin:APP:caelus.mixins.json:MixinLivingEntity,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:curioofundying.mixins.json:LivingEntityMixin,pl:mixin:APP:enhancedcelestials.mixins.json:MixinLivingEntity,pl:mixin:APP:supplementaries.mixins.json:LivingEntityLadderMixin,pl:mixin:A}
	at net.minecraft.world.entity.Mob.m_8119_(Mob.java:303) ~[server-1.17.1-20210706.113038-srg.jar%23143!:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:623) ~[server-1.17.1-20210706.113038-srg.jar%23143!:?] {re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:id,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:id,pl:mixin:APP:enhancedcelestials.mixins.json:MixinServerWorld,pl:mixin:A}
	at net.minecraft.world.level.Level.m_46653_(Level.java:486) ~[server-1.17.1-20210706.113038-srg.jar%23143!:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:twilightforest:hitbox,re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:hitbox,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:hitbox,pl:mixin:APP:enhancedcelestials.mixins.json:MixinWorld,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_143264_(ServerLevel.java:384) ~[server-1.17.1-20210706.113038-srg.jar%23143!:?] {re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:id,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:id,pl:mixin:APP:enhancedcelestials.mixins.json:MixinServerWorld,pl:mixin:A}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(SourceFile:54) ~[server-1.17.1-20210706.113038-srg.jar%23143!:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:365) ~[server-1.17.1-20210706.113038-srg.jar%23143!:?] {re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:id,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:id,pl:mixin:APP:enhancedcelestials.mixins.json:MixinServerWorld,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:883) ~[server-1.17.1-20210706.113038-srg.jar%23143!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:334) ~[server-1.17.1-20210706.113038-srg.jar%23143!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:819) ~[server-1.17.1-20210706.113038-srg.jar%23143!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:684) ~[server-1.17.1-20210706.113038-srg.jar%23143!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.17.1-20210706.113038-srg.jar%23143!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}
"

### How do you trigger this bug?

1.teleport to "Nether1" waystone
2.Load nether
3.Server crash with thrown error above.
...

### Loader

Forge

### Loader Version

37.0.126

### Mod Version

1.17.1-5.3.0.0

### Relevant Log Outputs

https://pastebin.com/mNMnd1ac

**Comment by TheIllusiveC4** [comment]
Curious Elytra bug, update to 1.17.1-5.0.0.1.
